FROM node:16
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies (inside the container)
RUN npm install

# Copy the rest of the application files
COPY . .

# Start the application
CMD ["npm", "start"]
EXPOSE 8000
